"""add message limit fields to user

Revision ID: 9e5783099c96
Revises: b1b08a393e99
Create Date: 2026-03-11 14:57:58.070982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5783099c96'
down_revision = 'b1b08a393e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('message_reset_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('message_reset_date')
        batch_op.drop_column('message_count')

    # ### end Alembic commands ###
